// ─── EVENTS.JS ────────────────────────────────────────────────────────────
el('addEvBtn').addEventListener('click',function(){var n=el('evName').value.trim();if(!n){alert('Enter an event name.');return;}var ci=events.length%EVENT_COLORS.length,ev={id:'e'+Date.now(),name:n,date:el('evDate').value,desc:el('evDesc').value.trim(),dishes:{},invitees:{},color:EVENT_COLORS[ci]};db.ref('events/'+ev.id).set(ev);['evName','evDate','evDesc'].forEach(function(i){el(i).value='';});});
function renderEvents(){var container=el('evList');if(!events.length){container.innerHTML='<div class="emp"><span>📅</span>No events yet!</div>';return;}var sorted=events.slice().sort(function(a,b){return(a.date||'9999')<(b.date||'9999')?-1:1;});var isAdmin=userName===ADMIN;container.innerHTML=sorted.map(function(ev){var dishes=ev.dishes?Object.values(ev.dishes):[],ec=ev.color||EVENT_COLORS[0],invitees=ev.invitees?Object.keys(ev.invitees):[];return'<div class="card" style="border-left:5px solid '+ec+'"><div style="display:flex;justify-content:space-between;align-items:flex-start"><div><b style="font-size:.97rem;color:'+ec+'">'+esc(ev.name)+'</b>'+(ev.date?'<br><span class="evbadge" style="background:'+ec+'">'+fmtDate(ev.date)+'</span>':'')+(ev.desc?'<p style="font-size:.84rem;color:var(--muted);margin-top:4px">'+esc(ev.desc)+'</p>':'')+'</div><div style="display:flex;gap:5px;flex-direction:column">'+(isAdmin?'<button class="xbtn" data-delev="'+ev.id+'">🗑</button>':'')+'<button class="sm ss" style="font-size:.72rem;padding:3px 8px" data-evinvite="'+ev.id+'">Invite</button></div></div>'+(invitees.length?'<div style="margin-top:8px;display:flex;flex-wrap:wrap;gap:4px">'+invitees.map(function(n){var col=members[n]?members[n].color:'#8A7A6E';return avt(n,col,24);}).join('')+'</div>':'')+'<div style="margin-top:11px"><div style="font-size:.74rem;font-weight:700;color:var(--muted);text-transform:uppercase;margin-bottom:7px">Bringing What</div>'+dishes.map(function(d){return'<div class="drow'+(d.by?' claimed':'')+'"><input type="checkbox" class="dchk"'+(d.by?' checked':'')+' data-dci="'+d.id+'" data-dev="'+ev.id+'"><span class="dnam">'+esc(d.name)+'</span>'+(d.by?'<span class="dwho">'+esc(d.by)+'</span>':'')+(!d.by&&isAdmin?'<button class="xbtn" data-deld="'+d.id+'" data-dev="'+ev.id+'">x</button>':'')+'</div>';}).join('')+'<div class="dacwrap" id="dac-'+ev.id+'"><input class="dacinp" id="dacinp-'+ev.id+'" type="text" placeholder="Type dish..." autocomplete="off"><div class="daclist" id="daclist-'+ev.id+'"></div></div><button class="dadb" data-dadd="'+ev.id+'">+ Add Dish</button></div></div>';}).join('');events.forEach(function(ev){var inp=el('dacinp-'+ev.id),list=el('daclist-'+ev.id);if(!inp||!list)return;inp.addEventListener('input',function(){var q=inp.value.toLowerCase();list.innerHTML='';if(!q){list.style.display='none';return;}var m=recipes.filter(function(r){return r.name.toLowerCase().indexOf(q)>-1;}).slice(0,6);if(!m.length){list.style.display='none';return;}list.style.display='block';list.innerHTML=m.map(function(r){return'<div class="dacitem" data-recname="'+esc(r.name)+'" data-evid="'+ev.id+'">'+esc(r.name)+'</div>';}).join('');});inp.addEventListener('keydown',function(e){if(e.key==='Enter'){e.preventDefault();addDish(ev.id);}});});}
function addDish(evid){var inp=el('dacinp-'+evid);if(!inp||!inp.value.trim())return;var list=el('daclist-'+evid);if(list)list.style.display='none';var did='d'+Date.now();db.ref('events/'+evid+'/dishes/'+did).set({id:did,name:inp.value.trim(),by:''});inp.value='';inp.focus();}
el('evInviteCancel').addEventListener('click',function(){el('evInviteMod').classList.add('h');});
el('evInviteSave').addEventListener('click',function(){if(!evInviteId)return;el('evInviteSelect').querySelectorAll('.mem-chip.on').forEach(function(chip){db.ref('events/'+evInviteId+'/invitees/'+chip.dataset.invitemem).set(true);});el('evInviteMod').classList.add('h');alert('Invites sent!');});

document.addEventListener('DOMContentLoaded',function(){
  el('addEvBtn').addEventListener('click',function(){var n=el('evName').value.trim();if(!n){alert('Enter an event name.');return;}var ci=events.length%EVENT_COLORS.length,ev={id:'e'+Date.now(),name:n,date:el('evDate').value,desc:el('evDesc').value.trim(),dishes:{},invitees:{},color:EVENT_COLORS[ci]};db.ref('events/'+ev.id).set(ev);['evName','evDate','evDesc'].forEach(function(i){el(i).value='';});});
  el('evInviteCancel').addEventListener('click',function(){el('evInviteMod').classList.add('h');});
  el('evInviteSave').addEventListener('click',function(){if(!evInviteId)return;el('evInviteSelect').querySelectorAll('.mem-chip.on').forEach(function(chip){db.ref('events/'+evInviteId+'/invitees/'+chip.dataset.invitemem).set(true);});el('evInviteMod').classList.add('h');alert('Invites sent!');});
});
