// ─── RECIPES.JS ───────────────────────────────────────────────────────────
function buildPresetTags(){var w=el('presetTags');if(!w)return;w.innerHTML=PRESET_TAGS.map(function(t){var on=selectedPresetTags.indexOf(t)>-1;return'<span class="tag'+(on?' on':'')+'" data-preset="'+esc(t)+'">'+esc(t)+'</span>';}).join('');}
function buildCatFilter(){var cats={};recipes.forEach(function(r){if(r.cat)cats[r.cat]=true;});var html='<span class="tag'+(activeCat===''?' on':'')+'" data-cat="">All</span>';PRESET_CATS.forEach(function(c){if(cats[c])html+='<span class="tag'+(activeCat===c?' on':'')+'" data-cat="'+esc(c)+'">'+esc(c)+'</span>';});el('catFilter').innerHTML=html;}
function buildTagFilter(){var tags={};recipes.forEach(function(r){(r.tags||[]).forEach(function(t){tags[t]=true;});});var html='<span class="tag'+(activeTag===''?' on':'')+'" data-tag="">All Tags</span>';Object.keys(tags).forEach(function(t){html+='<span class="tag'+(activeTag===t?' on':'')+'" data-tag="'+esc(t)+'">'+esc(t)+'</span>';});el('tagFilter').innerHTML=html;}
function getAvgRating(r){var rats=r.ratings?Object.values(r.ratings):[];if(!rats.length)return{avg:0,count:0};return{avg:rats.reduce(function(a,b){return a+b.stars;},0)/rats.length,count:rats.length};}
function starsHtml(rid,myR,ed){var h='<div class="stars">';for(var i=1;i<=5;i++)h+='<span class="star'+(i<=myR?' on':'')+'" data-star="'+i+'" data-rid="'+rid+'"'+(ed?'':' style="cursor:default"')+'>&#x2605;</span>';return h+'</div>';}
function avgStarsHtml(avg,rid){var pfx=rid?'id="avgr-'+rid+'"':'';var h='<div class="avg-stars" '+pfx+'>';for(var i=1;i<=5;i++)h+='<span class="avg-star'+(avg>=i?' on':'')+'">&#x2605;</span>';return h+'</div>';}

el('addRecBtn').addEventListener('click',function(){var n=el('rName').value.trim();if(!n){alert('Enter a recipe name.');return;}var allTags=selectedPresetTags.slice();el('rTags').value.split(',').map(function(s){return s.trim().toLowerCase();}).filter(Boolean).forEach(function(t){if(allTags.indexOf(t)<0)allTags.push(t);});var rec={id:'r'+Date.now(),name:n,cat:el('rCat').value||'Other',servings:el('rServings').value||'',diff:el('rDiff').value||'',tags:allTags,ings:el('rIngs').value.split(',').map(function(s){return s.trim();}).filter(Boolean),steps:el('rSteps').value.trim(),by:userName||'Family',notes:{},ratings:{},photo:'',testing:false};db.ref('recipes/'+rec.id).set(rec);['rName','rTags','rIngs','rSteps','rServings'].forEach(function(i){el(i).value='';});el('rCat').value='';el('rDiff').value='';selectedPresetTags=[];buildPresetTags();});
el('rSearch').addEventListener('input',renderRecipes);
function buildCatFilter(){var cats={};recipes.forEach(function(r){if(r.cat)cats[r.cat]=true;});var html='<span class="tag'+(activeCat===''?' on':'')+'" data-cat="">All</span>';PRESET_CATS.forEach(function(c){if(cats[c])html+='<span class="tag'+(activeCat===c?' on':'')+'" data-cat="'+esc(c)+'">'+esc(c)+'</span>';});el('catFilter').innerHTML=html;}
function buildTagFilter(){var tags={};recipes.forEach(function(r){(r.tags||[]).forEach(function(t){tags[t]=true;});});var html='<span class="tag'+(activeTag===''?' on':'')+'" data-tag="">All Tags</span>';Object.keys(tags).forEach(function(t){html+='<span class="tag'+(activeTag===t?' on':'')+'" data-tag="'+esc(t)+'">'+esc(t)+'</span>';});el('tagFilter').innerHTML=html;}
function getAvgRating(r){var rats=r.ratings?Object.values(r.ratings):[];if(!rats.length)return{avg:0,count:0};return{avg:rats.reduce(function(a,b){return a+b.stars;},0)/rats.length,count:rats.length};}
function starsHtml(rid,myR,ed){var h='<div class="stars">';for(var i=1;i<=5;i++)h+='<span class="star'+(i<=myR?' on':'')+'" data-star="'+i+'" data-rid="'+rid+'"'+(ed?'':' style="cursor:default"')+'>&#x2605;</span>';return h+'</div>';}
function avgStarsHtml(avg,rid){var pfx=rid?'id="avgr-'+rid+'"':'';var h='<div class="avg-stars" '+pfx+'>';for(var i=1;i<=5;i++)h+='<span class="avg-star'+(avg>=i?' on':'')+'">&#x2605;</span>';return h+'</div>';}
function renderRecipes(){
  var container=el('recList');var q=el('rSearch').value.toLowerCase();
  var list=recipes.filter(function(r){var ms=!q||r.name.toLowerCase().indexOf(q)>-1||(r.tags||[]).some(function(t){return t.indexOf(q)>-1;})||(r.cat||'').toLowerCase().indexOf(q)>-1;var mt=!activeTag||(r.tags||[]).indexOf(activeTag)>-1;var mc=!activeCat||(r.cat||'')===activeCat;return ms&&mt&&mc;});
  if(!list.length){container.innerHTML='<div class="emp"><span>📖</span>No recipes found!</div>';return;}
  var isAdmin=userName===ADMIN;var diffC={easy:'#eaf3ea',medium:'#fff8e1',hard:'#ffeaea'};var diffL={easy:'Easy',medium:'Medium',hard:'Hard'};
  container.innerHTML=list.map(function(r){
    var notes=r.notes?Object.values(r.notes):[];var rd=getAvgRating(r);var myR=r.ratings&&r.ratings[userName]?r.ratings[userName].stars:0;
    return'<div class="rc">'+
      '<div style="display:flex;justify-content:space-between;align-items:flex-start"><div style="flex:1">'+
        (r.photo?'<img src="'+esc(r.photo)+'" style="width:100%;max-height:160px;object-fit:cover;border-radius:9px;margin-bottom:9px;cursor:pointer" data-viewimg="'+esc(r.photo)+'" alt="">':'')+
        '<b style="font-size:.96rem">'+esc(r.name)+'</b>'+
        '<div style="display:flex;gap:6px;flex-wrap:wrap;align-items:center;margin-top:4px">'+
          '<span style="background:#f0e8ff;color:#6a3a9a;border:1px solid #c4a0f0;padding:2px 8px;border-radius:20px;font-size:.74rem;font-weight:600">'+esc(r.cat||'')+'</span>'+
          (r.servings?'<span style="font-size:.74rem;color:var(--muted)">Serves '+esc(r.servings)+'</span>':'')+
          (r.diff?'<span style="background:'+diffC[r.diff]+';padding:2px 8px;border-radius:20px;font-size:.74rem;font-weight:600">'+diffL[r.diff]+'</span>':'')+
          '<span style="font-size:.74rem;color:var(--muted)">by '+esc(r.by)+'</span>'+
        '</div>'+
        '<div style="margin-top:4px">'+(r.tags||[]).map(function(t){return'<span class="tag" style="cursor:default">'+esc(t)+'</span>';}).join('')+'</div>'+
        '<div style="display:flex;align-items:center;gap:6px;margin-top:5px;flex-wrap:wrap">'+avgStarsHtml(rd.avg,r.id)+'<span class="rating-count" id="avgc-'+r.id+'">'+(rd.count?rd.avg.toFixed(1)+' ('+rd.count+')':'No ratings')+'</span></div>'+
        (userName?'<div style="margin-top:3px;display:flex;align-items:center;gap:5px"><span style="font-size:.73rem;color:var(--muted)">Your rating:</span>'+starsHtml(r.id,myR,true)+'</div>':'')+
      '</div>'+
      '<div style="display:flex;flex-direction:column;gap:3px;flex-shrink:0;margin-left:7px">'+
        (userName?'<button class="obn obt" data-editr="'+r.id+'" style="font-size:.7rem;padding:3px 7px">Edit</button>':'')+
        (isAdmin?'<button class="xbtn" data-delr="'+r.id+'">🗑</button>':'')+
      '</div></div>'+
      '<div class="rbtns"><button class="obn" data-togr="'+r.id+'">View</button><button class="obn obt" data-cookr="'+r.id+'">Cook</button><button class="obn" data-printr="'+r.id+'" style="border-color:#888;color:#888">Print</button>'+(userName?'<label class="obn obs" style="cursor:pointer">Photo<input type="file" accept="image/*" data-photor="'+r.id+'" style="display:none"></label>':'')+'</div>'+
      '<div class="eform" id="ef-'+r.id+'"><input type="text" id="en-'+r.id+'" value="'+esc(r.name)+'"><select id="ec-'+r.id+'">'+PRESET_CATS.map(function(c){return'<option'+(r.cat===c?' selected':'')+'>'+c+'</option>';}).join('')+'</select><input type="text" id="et-'+r.id+'" value="'+esc((r.tags||[]).join(', '))+'" placeholder="Tags"><input type="number" id="esv-'+r.id+'" value="'+esc(r.servings||'')+'" placeholder="Servings"><select id="edf-'+r.id+'"><option value="">Difficulty</option><option value="easy"'+(r.diff==='easy'?' selected':'')+'>Easy</option><option value="medium"'+(r.diff==='medium'?' selected':'')+'>Medium</option><option value="hard"'+(r.diff==='hard'?' selected':'')+'>Hard</option></select><input type="text" id="ei-'+r.id+'" value="'+esc((r.ings||[]).join(', '))+'" placeholder="Ingredients"><textarea id="es-'+r.id+'">'+esc(r.steps||'')+'</textarea><div style="display:flex;gap:6px"><button class="sm st" data-saver="'+r.id+'">Save</button><button class="sm sx" data-canceledit="'+r.id+'">Cancel</button></div></div>'+
      '<div class="rbody" id="rb-'+r.id+'">'+
        (r.ings&&r.ings.length?'<h4>Ingredients</h4><ul>'+r.ings.map(function(i){return'<li>'+esc(i)+'</li>';}).join('')+'</ul>':'')+
        (r.steps?'<h4>Method</h4><p>'+esc(r.steps)+'</p>':'')+
        '<h4 style="margin-top:9px">Family Notes</h4>'+notes.map(function(n){var bg=n.color||'#8A7A6E';return'<div class="note"><span>'+esc(n.text)+'</span><div style="flex-shrink:0"><span class="nwho" style="background:'+bg+'">'+esc(n.by)+'</span>'+(isAdmin?'<button class="xbtn" data-delnote="'+n.id+'" data-recid="'+r.id+'">x</button>':'')+'</div></div>';}).join('')+
        '<div class="nadd"><input type="text" placeholder="Add a note..." id="ni-'+r.id+'"><button class="sm ss" data-addnote="'+r.id+'">Add</button></div>'+
      '</div></div>';
  }).join('');
}
function printRecipe(rec){var win=window.open('','_blank');var ings=rec.ings&&rec.ings.length?'<h3>Ingredients</h3><ul>'+rec.ings.map(function(i){return'<li>'+i+'</li>';}).join('')+'</ul>':'';var steps=rec.steps?'<h3>Method</h3>'+rec.steps.split('\n').filter(Boolean).map(function(s,i){return'<div style="margin-bottom:10px"><strong>Step '+(i+1)+':</strong> '+s+'</div>';}).join(''):'';win.document.write('<!DOCTYPE html><html><head><title>'+rec.name+'</title><style>body{font-family:Georgia,serif;max-width:700px;margin:40px auto;padding:20px;color:#2A2218}h1{color:#B8967E;border-bottom:2px solid #B8967E;padding-bottom:10px}h3{color:#8A7A6E;margin-top:20px}ul{padding-left:18px}li{margin-bottom:6px;line-height:1.6}@media print{button{display:none}}</style></head><body><h1>'+rec.name+'</h1>'+(rec.by?'<p style="color:#8a7d70;font-size:.88rem">by '+rec.by+'</p>':'')+ings+steps+'<button onclick="window.print()" style="margin-top:20px;padding:8px 20px;background:#B8967E;color:#fff;border:none;border-radius:8px;cursor:pointer">Print</button></body></html>');win.document.close();setTimeout(function(){win.print();},300);}
function startCook(rec){el('ckTitle').textContent=rec.name;currentPrintRec=rec;var parsed=(rec.ings||[]).map(parseIng);ckSteps=(rec.steps||'').split('\n').map(function(s){return s.trim();}).filter(Boolean);ckIdx=0;ckAll=false;el('ckAllBtn').textContent='All Steps';var ingHtml='<div id="ck-ingpage"><div class="cksect">Gather Your Ingredients</div><ul class="ckingl">'+parsed.map(function(p){return'<li><span class="ckqty">'+(p.q?esc(p.q):'&mdash;')+'</span><span class="cknam">'+esc(p.n)+'</span></li>';}).join('')+'</ul><button class="cknav" onclick="showCookSteps()" style="width:100%;margin-top:7px">Ready to Cook!</button></div><div id="ck-steps" style="display:none"><div class="cksect">Method</div><div id="ck-swrap">'+ckSteps.map(function(step,i){return'<div class="ckstep'+(i===0?' on':'')+'" id="cks-'+i+'"><div class="cklbl">Step '+(i+1)+' of '+ckSteps.length+'</div><div class="cktxt">'+esc(step)+'</div></div>';}).join('')+'</div></div>';el('ckBody').innerHTML=ingHtml;el('ckPrev').style.visibility='hidden';el('ckNext').style.visibility='hidden';el('ckProg').textContent='Ingredients';el('cookMode').classList.add('on');}
function showCookSteps(){el('ck-ingpage').style.display='none';el('ck-steps').style.display='block';el('ckPrev').style.visibility='visible';el('ckNext').style.visibility='visible';updateCkNav();}
function updateCkNav(){el('ckPrev').disabled=ckIdx===0;el('ckNext').disabled=ckIdx>=ckSteps.length-1;el('ckProg').textContent='Step '+(ckIdx+1)+' of '+ckSteps.length;}
el('ckPrev').addEventListener('click',function(){var o=el('cks-'+ckIdx);if(o&&!ckAll)o.classList.remove('on');ckIdx=Math.max(0,ckIdx-1);var c=el('cks-'+ckIdx);if(c){if(!ckAll)c.classList.add('on');c.scrollIntoView({behavior:'smooth',block:'nearest'});}updateCkNav();});
el('ckNext').addEventListener('click',function(){var o=el('cks-'+ckIdx);if(o&&!ckAll)o.classList.remove('on');ckIdx=Math.min(ckSteps.length-1,ckIdx+1);var c=el('cks-'+ckIdx);if(c){if(!ckAll)c.classList.add('on');c.scrollIntoView({behavior:'smooth',block:'nearest'});}updateCkNav();});
el('ckAllBtn').addEventListener('click',function(){ckAll=!ckAll;var w=el('ck-swrap');if(!w)return;w.querySelectorAll('.ckstep').forEach(function(s){s.classList.toggle('ons',ckAll);});el('ckAllBtn').textContent=ckAll?'Step Mode':'All Steps';});
el('ckExitBtn').addEventListener('click',function(){el('cookMode').classList.remove('on');});
el('ckPrintBtn').addEventListener('click',function(){if(currentPrintRec)printRecipe(currentPrintRec);});

function printRecipe(rec){var win=window.open('','_blank');var ings=rec.ings&&rec.ings.length?'<h3>Ingredients</h3><ul>'+rec.ings.map(function(i){return'<li>'+i+'</li>';}).join('')+'</ul>':'';var steps=rec.steps?'<h3>Method</h3>'+rec.steps.split('\n').filter(Boolean).map(function(s,i){return'<div style="margin-bottom:10px"><strong>Step '+(i+1)+':</strong> '+s+'</div>';}).join(''):'';win.document.write('<!DOCTYPE html><html><head><title>'+rec.name+'</title><style>body{font-family:Georgia,serif;max-width:700px;margin:40px auto;padding:20px;color:#2A2218}h1{color:#B8967E;border-bottom:2px solid #B8967E;padding-bottom:10px}h3{color:#8A7A6E;margin-top:20px}ul{padding-left:18px}li{margin-bottom:6px;line-height:1.6}@media print{button{display:none}}</style></head><body><h1>'+rec.name+'</h1>'+(rec.by?'<p style="color:#8a7d70;font-size:.88rem">by '+rec.by+'</p>':'')+ings+steps+'<button onclick="window.print()" style="margin-top:20px;padding:8px 20px;background:#B8967E;color:#fff;border:none;border-radius:8px;cursor:pointer">Print</button></body></html>');win.document.close();setTimeout(function(){win.print();},300);}
function startCook(rec){el('ckTitle').textContent=rec.name;currentPrintRec=rec;var parsed=(rec.ings||[]).map(parseIng);ckSteps=(rec.steps||'').split('\n').map(function(s){return s.trim();}).filter(Boolean);ckIdx=0;ckAll=false;el('ckAllBtn').textContent='All Steps';var ingHtml='<div id="ck-ingpage"><div class="cksect">Gather Your Ingredients</div><ul class="ckingl">'+parsed.map(function(p){return'<li><span class="ckqty">'+(p.q?esc(p.q):'&mdash;')+'</span><span class="cknam">'+esc(p.n)+'</span></li>';}).join('')+'</ul><button class="cknav" onclick="showCookSteps()" style="width:100%;margin-top:7px">Ready to Cook!</button></div><div id="ck-steps" style="display:none"><div class="cksect">Method</div><div id="ck-swrap">'+ckSteps.map(function(step,i){return'<div class="ckstep'+(i===0?' on':'')+'" id="cks-'+i+'"><div class="cklbl">Step '+(i+1)+' of '+ckSteps.length+'</div><div class="cktxt">'+esc(step)+'</div></div>';}).join('')+'</div></div>';el('ckBody').innerHTML=ingHtml;el('ckPrev').style.visibility='hidden';el('ckNext').style.visibility='hidden';el('ckProg').textContent='Ingredients';el('cookMode').classList.add('on');}
function showCookSteps(){el('ck-ingpage').style.display='none';el('ck-steps').style.display='block';el('ckPrev').style.visibility='visible';el('ckNext').style.visibility='visible';updateCkNav();}
function updateCkNav(){el('ckPrev').disabled=ckIdx===0;el('ckNext').disabled=ckIdx>=ckSteps.length-1;el('ckProg').textContent='Step '+(ckIdx+1)+' of '+ckSteps.length;}

document.addEventListener('DOMContentLoaded',function(){
  el('addRecBtn').addEventListener('click',function(){var n=el('rName').value.trim();if(!n){alert('Enter a recipe name.');return;}var allTags=selectedPresetTags.slice();el('rTags').value.split(',').map(function(s){return s.trim().toLowerCase();}).filter(Boolean).forEach(function(t){if(allTags.indexOf(t)<0)allTags.push(t);});var rec={id:'r'+Date.now(),name:n,cat:el('rCat').value||'Other',servings:el('rServings').value||'',diff:el('rDiff').value||'',tags:allTags,ings:el('rIngs').value.split(',').map(function(s){return s.trim();}).filter(Boolean),steps:el('rSteps').value.trim(),by:userName||'Family',notes:{},ratings:{},photo:'',testing:false};db.ref('recipes/'+rec.id).set(rec);['rName','rTags','rIngs','rSteps','rServings'].forEach(function(i){el(i).value='';});el('rCat').value='';el('rDiff').value='';selectedPresetTags=[];buildPresetTags();});
  el('rSearch').addEventListener('input',renderRecipes);
  el('ckPrev').addEventListener('click',function(){var o=el('cks-'+ckIdx);if(o&&!ckAll)o.classList.remove('on');ckIdx=Math.max(0,ckIdx-1);var c=el('cks-'+ckIdx);if(c){if(!ckAll)c.classList.add('on');c.scrollIntoView({behavior:'smooth',block:'nearest'});}updateCkNav();});
  el('ckNext').addEventListener('click',function(){var o=el('cks-'+ckIdx);if(o&&!ckAll)o.classList.remove('on');ckIdx=Math.min(ckSteps.length-1,ckIdx+1);var c=el('cks-'+ckIdx);if(c){if(!ckAll)c.classList.add('on');c.scrollIntoView({behavior:'smooth',block:'nearest'});}updateCkNav();});
  el('ckAllBtn').addEventListener('click',function(){ckAll=!ckAll;var w=el('ck-swrap');if(!w)return;w.querySelectorAll('.ckstep').forEach(function(s){s.classList.toggle('ons',ckAll);});el('ckAllBtn').textContent=ckAll?'Step Mode':'All Steps';});
  el('ckExitBtn').addEventListener('click',function(){el('cookMode').classList.remove('on');});
  el('ckPrintBtn').addEventListener('click',function(){if(currentPrintRec)printRecipe(currentPrintRec);});
  el('fmtClear').addEventListener('click',function(){el('fmtInput').value='';el('fmtResult').innerHTML='';el('fmtResult').classList.remove('on');});
  el('fmtBtn').addEventListener('click',function(){var raw=el('fmtInput').value.trim();if(!raw){alert('Paste a recipe first!');return;}var res=el('fmtResult');res.classList.add('on');res.innerHTML='<div class="ai-loading">Formatting your recipe...</div>';fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:'claude-sonnet-4-20250514',max_tokens:1000,messages:[{role:'user',content:'Format this recipe into clean sections. Return ONLY JSON with keys: name, category (one of: Breakfast/Mains/Chicken/Beef/Lamb/Pork/Seafood/Vegetarian/Vegan/Salads/Soups/Sides/Snacks/Desserts/Sweet Treats/Cakes/Breads/Drinks/Other), servings (number only), ingredients (array of strings), steps (array of strings). No markdown, no preamble, just JSON.\n\nRecipe:\n'+raw}]})}).then(function(r){return r.json();}).then(function(data){try{var txt=data.content.map(function(i){return i.text||'';}).join('');var clean=txt.replace(/```json|```/g,'').trim();var parsed=JSON.parse(clean);res.innerHTML='<div style="font-weight:700;font-size:1rem;margin-bottom:8px;color:var(--terra)">'+esc(parsed.name||'Recipe')+'</div>'+(parsed.ingredients&&parsed.ingredients.length?'<div style="font-weight:700;font-size:.8rem;color:var(--muted);text-transform:uppercase;margin-bottom:5px">Ingredients</div><ul style="padding-left:16px;margin-bottom:12px">'+parsed.ingredients.map(function(i){return'<li style="font-size:.87rem;margin-bottom:3px">'+esc(i)+'</li>';}).join('')+'</ul>':'')+(parsed.steps&&parsed.steps.length?'<div style="font-weight:700;font-size:.8rem;color:var(--muted);text-transform:uppercase;margin-bottom:5px">Method</div>'+parsed.steps.map(function(s,i){return'<div style="font-size:.87rem;margin-bottom:8px;padding:6px 9px;background:#fff;border-radius:7px;border:1px solid var(--border)"><strong>Step '+(i+1)+':</strong> '+esc(s)+'</div>';}).join(''):'')+'<div style="display:flex;gap:8px;margin-top:12px"><button class="btn" style="font-size:.82rem;padding:7px 14px" data-usefmt=\''+JSON.stringify(parsed).replace(/'/g,"&#39;")+'\'>Use This Recipe</button><button class="sm sx" id="fmtClear2">Clear</button></div>';el('fmtClear2').addEventListener('click',function(){res.innerHTML='';res.classList.remove('on');el('fmtInput').value='';});}catch(err){res.innerHTML='<p style="color:var(--re);font-size:.85rem">Could not parse. Please try again.</p>';}}).catch(function(){res.innerHTML='<p style="color:var(--re);font-size:.85rem">AI formatting failed.</p>';});});
el('fmtClear').addEventListener('click',function(){el('fmtInput').value='';el('fmtResult').innerHTML='';el('fmtResult').classList.remove('on');});
});
